export { default as Case } from './Case'
export { default as Death } from './Death'
export { default as Dots } from './Dots'
export { default as Home } from './Home'
export { default as Recovered } from './Recovered'
export { default as Search } from './Search'
export { default as Settings } from './Settings'
export { default as Sick } from './Sick'